### ISSUE TITLE
Add example?

### ISSUE THREAD

**Issue by kenpusney** [PragmaTwice/ChthollyLang#3]

**Comment by PragmaTwice** [comment]
Done, thx. 
At [80fa770](https://github.com/PragmaTwice/ChthollyLang/commit/80fa7708eb48d1188ab67bed5adf22b36f9e5f8a) and [demo/parser.cpp](https://github.com/PragmaTwice/ChthollyLang/blob/master/demo/parser.cpp).

**Comment by kenpusney** [comment]
... I mean, the example in Chtholly lang, not a working demo of this interpreter.

**Comment by PragmaTwice** [comment]
You'll find some example used in unit testing at  [test/parser-test.cpp](https://github.com/PragmaTwice/ChthollyLang/blob/master/test/parser-test.cpp).

I want to focus myself on interpreter development.
And when I has done, examples and other language-introduction tools will appear.
